pr: none
trigger:
 batch: true
 branches:
   include:
     - develop
 paths:
  include:
    - Core.Cloud.Services.TransactionService.AzureDeploy/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

